[package]
name = "mario"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.18" }
hyper = "0.14.26"
indoc = "2.0.1"
serde = "1.0.162"
tokio = { version = "1.28.0", features = ["full"] }
tower = "0.4.13"
